packages:
  - ./
catalog:
  '@antfu/eslint-config': ^4.13.3
  '@atinux/kysely-d1': ^0.3.1
  '@iconify-json/heroicons': ^1.2.2
  '@iconify-json/simple-icons': ^1.2.37
  '@iconify/utils': ^2.3.0
  '@nuxt/content': ^3.5.1
  '@nuxt/eslint': ^1.4.1
  '@nuxt/eslint-config': ^1.4.1
  '@nuxthub/core': ^0.8.27
  '@nuxtjs/color-mode': ^3.5.2
  '@unocss/nuxt': ^66.1.3
  '@vueuse/core': ^13.3.0
  '@vueuse/nuxt': ^13.3.0
  better-auth: 1.2.8
  drizzle-kit: ^0.31.1
  drizzle-orm: ^0.44.2
  eslint: ^9.28.0
  eslint-plugin-format: ^1.0.1
  lint-staged: ^16.1.0
  marked: ^15.0.12
  motion: ^12.16.0
  motion-v: ^1.2.0
  nimiq-css: 1.0.0-beta.54
  nuxt: ^3.17.5
  nuxt-mcp: ^0.2.2
  nuxt-safe-runtime-config: ^0.0.3
  ofetch: ^1.4.1
  reka-ui: ^2.3.0
  typescript: ^5.8.3
  unocss: ^66.1.3
  unocss-preset-onmax: 1.0.0-beta.37
  valibot: ^1.1.0
  vue: ^3.5.16
  vue-router: ^4.5.1
  vue-tsc: ^2.2.10
  wrangler: ^4.19.1
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - better-sqlite3
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
  - vue-demi
  - workerd
